#
# golangci-lint
#
# For defaults, see:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
#
# 
#
run:
  timeout: 5m

linters:
  enable:
    - unconvert
    - prealloc
    - bodyclose

issues:
  exclude-rules:
    - linters:
        - staticcheck
      # Error Text:
      #   "SA9004: only the first constant in this group has an explicit type"
      # Efect:
      #   Allows short-hand first constant type declarations:
      # Example:
      #   const (
      #     Name  Type = "value"
      #     Name2      = "value2"
      #   )
      text: "SA9004:"  
