package scaffolding

import (
	"os"
	"path/filepath"
	"testing"

	"knative.dev/func/pkg/filesystem"
	. "knative.dev/func/pkg/testing"
)

func TestMiddlewareVersionDetector_Go(t *testing.T) {
	tests := []struct {
		Name    string // Name of the test
		GoMod   string // Gomod file
		Version string // Version Expected
		WantErr bool   // Error Expected
	}{
		{
			Name: "Version exists",
			GoMod: `
module s

replace function => ./f

go 1.21

require (
	function v0.0.0-00010101000000-000000000000
	knative.dev/func-go v0.21.3
)

require (
	github.com/mattn/go-colorable v0.1.13 // indirect
	github.com/mattn/go-isatty v0.0.20 // indirect
	github.com/rs/zerolog v1.32.0 // indirect
	golang.org/x/sys v0.18.0 // indirect
)
	`,
			Version: "v0.21.3",
			WantErr: false,
		}, {
			Name: "Version not found",
			GoMod: `
module s

replace function => ./f

go 1.21

require (
	function v0.0.0-00010101000000-000000000000
)

require (
	github.com/mattn/go-colorable v0.1.13 // indirect
	github.com/mattn/go-isatty v0.0.20 // indirect
	github.com/rs/zerolog v1.32.0 // indirect
	golang.org/x/sys v0.18.0 // indirect
)
	`,
			WantErr: true,
		},
	}

	for _, test := range tests {
		t.Run(test.Name, func(t *testing.T) {

			root, cleanup := Mktemp(t)
			defer cleanup()

			goModDir := filepath.Join(root, "go", "scaffolding", InstancedHTTP.String())
			if err := os.MkdirAll(goModDir, os.ModePerm); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(filepath.Join(goModDir, "go.mod"), []byte(test.GoMod), os.ModePerm); err != nil {
				t.Fatal(err)
			}

			d := &golangMiddlewareVersionDetector{}
			fs := filesystem.NewOsFilesystem(root)
			v, err := d.Detect(fs, InstancedHTTP)
			if (err != nil) != test.WantErr {
				t.Fatalf("got error %v, want error %v", err, test.WantErr)
			}

			if test.Version != v {
				t.Errorf("got version %s, want %s", test.Version, v)
			}
		})
	}
}

func TestMiddlewareVersionDetector_Python(t *testing.T) {
	tests := []struct {
		Name      string // Name of the test
		Pyproject string // Pyproject.toml file
		Version   string // Version Expected
		WantErr   bool   // Error Expected
	}{
		{
			Name: "Version exists",
			Pyproject: `
[project]
name = "service"
description = "an autogenerated service which runs a Function"
version = "0.1.0"
requires-python = ">=3.9"
readme = "README.md"
license = "MIT"
dependencies = [
    "func-python==0.7.0",
    "function @ {root:uri}/f"
]
authors = [
  { name="The Knative Authors", email="knative-dev@googlegroups.com"},
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.hatch.metadata]
allow-direct-references = true
	`,
			Version: "0.7.0",
			WantErr: false,
		}, {
			Name: "Dependency exists but without version",
			Pyproject: `
[project]
name = "service"
description = "an autogenerated service which runs a Function"
version = "0.1.0"
requires-python = ">=3.9"
readme = "README.md"
license = "MIT"
dependencies = [
    "func-python",
    "function @ {root:uri}/f"
]
authors = [
  { name="The Knative Authors", email="knative-dev@googlegroups.com"},
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.hatch.metadata]
allow-direct-references = true
	`,
			Version: "",
			WantErr: false,
		}, {
			Name: "Version not found",
			Pyproject: `
[project]
name = "service"
description = "an autogenerated service which runs a Function"
version = "0.1.0"
requires-python = ">=3.9"
readme = "README.md"
license = "MIT"
dependencies = [
    "function @ {root:uri}/f"
]
authors = [
  { name="The Knative Authors", email="knative-dev@googlegroups.com"},
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.hatch.metadata]
allow-direct-references = true
	`,
			WantErr: true,
		},
	}

	for _, test := range tests {
		t.Run(test.Name, func(t *testing.T) {

			root, cleanup := Mktemp(t)
			defer cleanup()

			pyprojectDir := filepath.Join(root, "python", "scaffolding", InstancedHTTP.String())
			if err := os.MkdirAll(pyprojectDir, os.ModePerm); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(filepath.Join(pyprojectDir, "pyproject.toml"), []byte(test.Pyproject), os.ModePerm); err != nil {
				t.Fatal(err)
			}

			d := &pythonMiddlewareVersionDetector{}
			fs := filesystem.NewOsFilesystem(root)
			v, err := d.Detect(fs, InstancedHTTP)
			if (err != nil) != test.WantErr {
				t.Fatalf("got error %v, want error %v", err, test.WantErr)
			}

			if test.Version != v {
				t.Errorf("got version %s, want %s", test.Version, v)
			}
		})
	}
}

func TestMiddlewareVersionDetector_Node(t *testing.T) {
	tests := []struct {
		Name        string // Name of the test
		ProjectJson string // project.json file
		Version     string // Version Expected
		WantErr     bool   // Error Expected
	}{
		{
			Name: "Version exists",
			ProjectJson: `
{
  "name": "http-handler",
  "version": "0.1.0",
  "description": "A function which responds to HTTP requests",
  "main": "index.js",
  "scripts": {
    "test": "node test/unit.js && node test/integration.js",
    "start": "FUNC_LOG_LEVEL=info faas-js-runtime ./index.js",
    "debug": "nodemon --inspect ./node_modules/faas-js-runtime/bin/cli.js ./index.js"
  },
  "keywords": [],
  "author": "",
  "license": "Apache-2.0",
  "dependencies": {
    "faas-js-runtime": "^2.4.0"
  },
  "devDependencies": {
    "nodemon": "^3.0.1",
    "supertest": "^6.3.1",
    "tape": "^5.0.1"
  }
}
	`,
			Version: "2.4.0",
			WantErr: false,
		}, {
			Name: "Version not found",
			ProjectJson: `
{
  "name": "http-handler",
  "version": "0.1.0",
  "description": "A function which responds to HTTP requests",
  "main": "index.js",
  "scripts": {
    "test": "node test/unit.js && node test/integration.js",
    "start": "FUNC_LOG_LEVEL=info faas-js-runtime ./index.js",
    "debug": "nodemon --inspect ./node_modules/faas-js-runtime/bin/cli.js ./index.js"
  },
  "keywords": [],
  "author": "",
  "license": "Apache-2.0",
  "dependencies": {},
  "devDependencies": {
    "nodemon": "^3.0.1",
    "supertest": "^6.3.1",
    "tape": "^5.0.1"
  }
}
	`,
			WantErr: true,
		},
	}

	for _, test := range tests {
		t.Run(test.Name, func(t *testing.T) {

			root, cleanup := Mktemp(t)
			defer cleanup()

			packageDir := filepath.Join(root, "node", "http")
			if err := os.MkdirAll(packageDir, os.ModePerm); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(filepath.Join(packageDir, "package.json"), []byte(test.ProjectJson), os.ModePerm); err != nil {
				t.Fatal(err)
			}

			d := &nodeMiddlewareVersionDetector{}
			fs := filesystem.NewOsFilesystem(root)
			v, err := d.Detect(fs, InstancedHTTP)
			if (err != nil) != test.WantErr {
				t.Fatalf("got error %v, want error %v", err, test.WantErr)
			}

			if test.Version != v {
				t.Errorf("got version %s, want %s", test.Version, v)
			}
		})
	}
}

func TestMiddlewareVersionDetector_Quarkus(t *testing.T) {
	tests := []struct {
		Name    string // Name of the test
		PomXml  string // pom.xml file
		Version string // Version Expected
		WantErr bool   // Error Expected
	}{
		{
			Name: "Version exists",
			PomXml: `
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.acme</groupId>
  <artifactId>function</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <properties>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
    <quarkus.platform.version>3.30.1</quarkus.platform.version>
  </properties>
  <dependencyManagement>
    <dependencies>
	</dependencies>
  </dependencyManagement>
</project>
	`,
			Version: "3.30.1",
			WantErr: false,
		}, {
			Name: "Version not found",
			PomXml: `
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.acme</groupId>
  <artifactId>function</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <properties>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
  </properties>
  <dependencyManagement>
    <dependencies>
	</dependencies>
  </dependencyManagement>
</project>
	`,
			WantErr: true,
		},
	}

	for _, test := range tests {
		t.Run(test.Name, func(t *testing.T) {

			root, cleanup := Mktemp(t)
			defer cleanup()

			pomDir := filepath.Join(root, "quarkus", "http")
			if err := os.MkdirAll(pomDir, os.ModePerm); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(filepath.Join(pomDir, "pom.xml"), []byte(test.PomXml), os.ModePerm); err != nil {
				t.Fatal(err)
			}

			d := &quarkusMiddlewareVersionDetector{}
			fs := filesystem.NewOsFilesystem(root)
			v, err := d.Detect(fs, InstancedHTTP)
			if (err != nil) != test.WantErr {
				t.Fatalf("got error %v, want error %v", err, test.WantErr)
			}

			if test.Version != v {
				t.Errorf("got version %s, want %s", test.Version, v)
			}
		})
	}
}

func TestMiddlewareVersionDetector_Java(t *testing.T) {
	tests := []struct {
		Name    string // Name of the test
		PomXml  string // pom.xml file
		Version string // Version Expected
		WantErr bool   // Error Expected
	}{
		{
			Name: "Version exists",
			PomXml: `
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.5.8</version>
    <relativePath/>
  </parent>
  <groupId>com.example.events</groupId>
  <artifactId>function</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>Spring Cloud Function::Http Example</name>
  <description>A Spring Cloud Function, Http Example</description>
  <properties>
    <java.version>21</java.version>
    <spring-cloud.version>2025.0.0</spring-cloud.version>
    <compiler-plugin.version>3.11.0</compiler-plugin.version>
  </properties>
  <dependencyManagement>
    <dependencies>
	</dependencies>
  </dependencyManagement>
</project>
	`,
			Version: "2025.0.0",
			WantErr: false,
		}, {
			Name: "Version not found",
			PomXml: `
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.5.8</version>
    <relativePath/>
  </parent>
  <groupId>com.example.events</groupId>
  <artifactId>function</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>Spring Cloud Function::Http Example</name>
  <description>A Spring Cloud Function, Http Example</description>
  <properties>
    <java.version>21</java.version>
    <compiler-plugin.version>3.11.0</compiler-plugin.version>
  </properties>
  <dependencyManagement>
    <dependencies>
	</dependencies>
  </dependencyManagement>
</project>
	`,
			WantErr: true,
		},
	}

	for _, test := range tests {
		t.Run(test.Name, func(t *testing.T) {

			root, cleanup := Mktemp(t)
			defer cleanup()

			pomDir := filepath.Join(root, "springboot", "http")
			if err := os.MkdirAll(pomDir, os.ModePerm); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(filepath.Join(pomDir, "pom.xml"), []byte(test.PomXml), os.ModePerm); err != nil {
				t.Fatal(err)
			}

			d := &springMiddlewareVersionDetector{}
			fs := filesystem.NewOsFilesystem(root)
			v, err := d.Detect(fs, InstancedHTTP)
			if (err != nil) != test.WantErr {
				t.Fatalf("got error %v, want error %v", err, test.WantErr)
			}

			if test.Version != v {
				t.Errorf("got version %s, want %s", test.Version, v)
			}
		})
	}
}
