apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-09-03T13:28:17Z"
  name: test-keda-no-kafka-interceptor-bridge
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: test-keda-no-kafka
    uid: e479851c-a037-4376-b546-99168f2fa679
  resourceVersion: "1290"
  uid: d1a5eea4-1cfd-4969-ad31-845be4aa4abe
spec:
  externalName: keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local
  sessionAffinity: None
  type: ExternalName
status:
  loadBalancer: {}
