package filesystem

import (
	"bufio"
	"bytes"
	"embed"
	"go/build/constraint"
	"io"
	"io/fs"
	"strings"
	"time"
)

// File-mangling constants shared with the hack/cmd/embd tool.
const (
	// EmbdSuffix is appended to go.mod and go.sum filenames so that go:embed
	// does not skip the directory (go:embed silently skips dirs with go.mod).
	EmbdSuffix = ".embd"

	// SymlinkSuffix is appended to symlink marker files. A file named
	// "foo.symlink" is a plain-text file whose content is the symlink target.
	// go:embed silently drops real symlinks, so we represent them this way.
	SymlinkSuffix = ".symlink"

	// EmbdBuildConstraint is the build-constraint tag name used to mark Go
	// source files inside templates/ so they are not compiled by go build.
	EmbdBuildConstraint = "embd"

	// PermissionsManifest is the name of the file listing non-default
	// permissions in the templates/ tree, generated by hack/cmd/permissiongen.
	PermissionsManifest = ".permissions"

	permissionsManifest = PermissionsManifest
)

// manglingFS wraps a Filesystem and transparently reverses on-disk name
// mangling applied to work around go:embed limitations:
//
//   - go.mod.embd / go.sum.embd  →  go.mod / go.sum
//     (go:embed skips directories containing go.mod; renaming avoids this)
//
//   - foo.symlink (regular file containing target path)  →  foo (symlink entry)
//     (go:embed silently drops symlinks; .symlink files are a workaround)
//
// Additionally, manglingFS:
//   - strips "//go:build embd" lines from file content so users never see them
//   - restores file permissions from .permissions manifest (embed.FS drops them)
//   - returns 0644 for regular files and 0755 for directories by default
type manglingFS struct {
	inner Filesystem
	// perms maps relative path → permission bits for files with non-default perms.
	// Default assumed for files: 0644. For dirs: 0755. Loaded from .permissions.
	perms map[string]fs.FileMode
}

// NewManglingFS creates a manglingFS wrapping the given embed.FS.
func NewManglingFS(inner embed.FS) manglingFS {
	adapted := embedFSAdapter{inner}
	return manglingFS{inner: adapted, perms: loadPerms(adapted)}
}

// NewManglingFilesystem creates a manglingFS wrapping any Filesystem.
// This is useful for testing with osFilesystem or billyFilesystem backends
// that serve a templates directory containing on-disk mangled files.
func NewManglingFilesystem(inner Filesystem) manglingFS {
	return manglingFS{inner: inner, perms: loadPerms(inner)}
}

// loadPerms reads the .permissions manifest from the filesystem and returns
// a map of path → permission bits for non-default files.
func loadPerms(fsys Filesystem) map[string]fs.FileMode {
	f, err := fsys.Open(permissionsManifest)
	if err != nil {
		return nil
	}
	defer f.Close()

	perms := make(map[string]fs.FileMode)
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		var mode uint32
		var path string
		if n, err := parsePermLine(line, &mode, &path); n == 2 && err == nil {
			perms[path] = fs.FileMode(mode)
		}
	}
	return perms
}

// parsePermLine parses a line like "0755 quarkus/cloudevents/mvnw".
func parsePermLine(line string, mode *uint32, path *string) (int, error) {
	var n int
	var err error
	_, err = func() (int, error) {
		parts := strings.SplitN(line, " ", 2)
		if len(parts) != 2 {
			return 0, io.ErrUnexpectedEOF
		}
		var m uint32
		for _, c := range parts[0] {
			if c < '0' || c > '7' {
				return 0, io.ErrUnexpectedEOF
			}
			m = m*8 + uint32(c-'0')
		}
		*mode = m
		*path = strings.TrimSpace(parts[1])
		n = 2
		return 2, nil
	}()
	return n, err
}

// permFor returns the effective permission for the named path (relative).
// Defaults to 0644 for files; .permissions entries override this.
func (m manglingFS) permFor(name string) fs.FileMode {
	if perm, ok := m.perms[name]; ok {
		return perm
	}
	return 0644
}

// Open opens the named file. If the file is not found, it also tries
// name + ".embd" (for go.mod / go.sum files).
func (m manglingFS) Open(name string) (fs.File, error) {
	f, err := m.inner.Open(name)
	if err != nil {
		// Try with .embd suffix (handles go.mod.embd, go.sum.embd)
		f2, err2 := m.inner.Open(name + ".embd")
		if err2 != nil {
			return nil, err // return original error
		}
		return &embdFile{File: f2, name: name, perm: m.permFor(name)}, nil
	}
	return &strippedFile{File: f, perm: m.permFor(name)}, nil
}

// Stat returns FileInfo for the named file.
func (m manglingFS) Stat(name string) (fs.FileInfo, error) {
	fi, err := m.inner.Stat(name)
	if err == nil {
		return &permFileInfo{FileInfo: fi, perm: m.permFor(name)}, nil
	}
	// Try .embd suffix
	fi2, err2 := m.inner.Stat(name + ".embd")
	if err2 == nil {
		return &mangledFileInfo{FileInfo: fi2, name: name, perm: m.permFor(name)}, nil
	}
	// Try .symlink suffix
	fi3, err3 := m.inner.Stat(name + ".symlink")
	if err3 == nil {
		return &symlinkFileInfo{FileInfo: fi3, name: name}, nil
	}
	return nil, err
}

// ReadDir lists the directory named by name, reversing name mangling on entries.
func (m manglingFS) ReadDir(name string) ([]fs.DirEntry, error) {
	entries, err := m.inner.ReadDir(name)
	if err != nil {
		return nil, err
	}
	result := make([]fs.DirEntry, 0, len(entries))
	for _, e := range entries {
		n := e.Name()

		// Build the relative path for permission lookup
		var rel string
		if name == "." || name == "" {
			rel = n
		} else {
			rel = name + "/" + n
		}

		switch {
		case strings.HasSuffix(n, ".embd"):
			// Strip .embd suffix — present go.mod / go.sum with real name
			bareRel := strings.TrimSuffix(rel, ".embd")
			result = append(result, &mangledDirEntry{
				DirEntry: e,
				name:     strings.TrimSuffix(n, ".embd"),
				perm:     m.permFor(bareRel),
			})
		case strings.HasSuffix(n, ".symlink"):
			// Present as a symlink DirEntry with the bare name
			result = append(result, &symlinkDirEntry{
				DirEntry: e,
				name:     strings.TrimSuffix(n, ".symlink"),
			})
		default:
			result = append(result, &permDirEntry{DirEntry: e, perm: m.permFor(rel)})
		}
	}
	return result, nil
}

// Readlink returns the target of the symlink at the given path by reading
// the corresponding .symlink marker file.
func (m manglingFS) Readlink(link string) (string, error) {
	f, err := m.inner.Open(link + ".symlink")
	if err != nil {
		return "", &fs.PathError{Op: "readlink", Path: link, Err: fs.ErrInvalid}
	}
	defer f.Close()
	bs, err := io.ReadAll(f)
	if err != nil {
		return "", err
	}
	// Trim trailing newline added to satisfy EOF-newline linting requirements.
	return strings.TrimRight(string(bs), "\n\r"), nil
}

// ---------------------------------------------------------------------------
// embedFSAdapter adapts embed.FS to the Filesystem interface.
// ---------------------------------------------------------------------------

type embedFSAdapter struct {
	inner embed.FS
}

func (a embedFSAdapter) Open(name string) (fs.File, error) {
	return a.inner.Open(name)
}

func (a embedFSAdapter) ReadDir(name string) ([]fs.DirEntry, error) {
	return a.inner.ReadDir(name)
}

func (a embedFSAdapter) Stat(name string) (fs.FileInfo, error) {
	f, err := a.inner.Open(name)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	return f.Stat()
}

func (a embedFSAdapter) Readlink(link string) (string, error) {
	return "", &fs.PathError{Op: "readlink", Path: link, Err: fs.ErrInvalid}
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// strippedFile strips "//go:build embd" build-constraint lines from file
// content. This prevents the constraint from appearing in scaffolded files.
type strippedFile struct {
	fs.File
	perm     fs.FileMode
	stripped bool
	buf      *bytes.Reader
}

func (s *strippedFile) Read(p []byte) (int, error) {
	if !s.stripped {
		raw, err := io.ReadAll(s.File)
		if err != nil {
			return 0, err
		}
		raw = stripEmbdBuildTag(raw)
		s.buf = bytes.NewReader(raw)
		s.stripped = true
	}
	return s.buf.Read(p)
}

func (s *strippedFile) Stat() (fs.FileInfo, error) {
	fi, err := s.File.Stat()
	if err != nil {
		return nil, err
	}
	return &permFileInfo{FileInfo: fi, perm: s.perm}, nil
}

// StripEmbdBuildTag removes the "embd" tag from the //go:build constraint in
// Go source bytes, using the go/build/constraint package for correct AST
// manipulation. It handles all forms:
//
//   - "//go:build embd"            → line (+ following blank line) removed
//   - "//go:build embd && <rest>"  → replaced with "//go:build <rest>"
//   - "//go:build embd || <rest>"  → replaced with "//go:build <rest>"
//   - any deeper nesting           → embd node pruned from the AST
//
// Lines that do not contain the "embd" tag are kept byte-for-byte unchanged.
func StripEmbdBuildTag(src []byte) []byte {
	lines := bytes.SplitAfter(src, []byte("\n"))
	out := make([]byte, 0, len(src))
	skipNext := false
	for _, line := range lines {
		trimmed := strings.TrimRight(string(line), "\r\n")
		if skipNext && trimmed == "" {
			skipNext = false
			continue
		}
		skipNext = false

		if !constraint.IsGoBuild(trimmed) {
			out = append(out, line...)
			continue
		}
		// Parse the //go:build line.
		expr, err := constraint.Parse(trimmed)
		if err != nil || !containsEmbdTag(expr) {
			// Not parseable or does not contain "embd" — keep unchanged.
			out = append(out, line...)
			continue
		}
		pruned := removeEmbdTag(expr)
		if pruned == nil {
			// The only tag was "embd" — drop the line and the blank after it.
			skipNext = true
			continue
		}
		out = append(out, []byte("//go:build "+pruned.String()+"\n")...)
	}
	return out
}

// AddEmbdBuildTag prepends or merges the "embd" build constraint into Go
// source bytes. If the file already has a //go:build line, the new constraint
// is ANDed with the existing one. Otherwise "//go:build embd\n\n" is prepended.
func AddEmbdBuildTag(src []byte) []byte {
	lines := bytes.SplitAfter(src, []byte("\n"))
	for i, line := range lines {
		trimmed := strings.TrimRight(string(line), "\r\n")
		if !constraint.IsGoBuild(trimmed) {
			continue
		}
		// Found an existing //go:build line — parse and merge.
		existing, err := constraint.Parse(trimmed)
		if err != nil {
			break
		}
		merged := &constraint.AndExpr{X: &constraint.TagExpr{Tag: EmbdBuildConstraint}, Y: existing}
		lines[i] = []byte("//go:build " + merged.String() + "\n")
		return bytes.Join(lines, nil)
	}
	// No existing constraint — prepend "//go:build embd\n\n".
	header := []byte("//go:build " + EmbdBuildConstraint + "\n\n")
	return append(header, src...)
}

// containsEmbdTag reports whether the expression tree contains the "embd" tag.
func containsEmbdTag(expr constraint.Expr) bool {
	switch e := expr.(type) {
	case *constraint.TagExpr:
		return e.Tag == EmbdBuildConstraint
	case *constraint.AndExpr:
		return containsEmbdTag(e.X) || containsEmbdTag(e.Y)
	case *constraint.OrExpr:
		return containsEmbdTag(e.X) || containsEmbdTag(e.Y)
	case *constraint.NotExpr:
		return containsEmbdTag(e.X)
	}
	return false
}

// removeEmbdTag recursively removes all occurrences of the "embd" Tag from a
// constraint.Expr AST. Returns nil when the entire expression collapses.
func removeEmbdTag(expr constraint.Expr) constraint.Expr {
	switch e := expr.(type) {
	case *constraint.TagExpr:
		if e.Tag == EmbdBuildConstraint {
			return nil
		}
		return e
	case *constraint.AndExpr:
		x := removeEmbdTag(e.X)
		y := removeEmbdTag(e.Y)
		if x == nil {
			return y
		}
		if y == nil {
			return x
		}
		return &constraint.AndExpr{X: x, Y: y}
	case *constraint.OrExpr:
		x := removeEmbdTag(e.X)
		y := removeEmbdTag(e.Y)
		if x == nil {
			return y
		}
		if y == nil {
			return x
		}
		return &constraint.OrExpr{X: x, Y: y}
	case *constraint.NotExpr:
		inner := removeEmbdTag(e.X)
		if inner == nil {
			return nil
		}
		return &constraint.NotExpr{X: inner}
	}
	return expr
}

// stripEmbdBuildTag is the package-internal alias for StripEmbdBuildTag.
func stripEmbdBuildTag(src []byte) []byte { return StripEmbdBuildTag(src) }

// embdFile wraps a file that was opened with a .embd suffix but
// exposes the original (non-.embd) name in Stat().
type embdFile struct {
	fs.File
	name     string
	perm     fs.FileMode
	stripped bool
	buf      *bytes.Reader
}

func (e *embdFile) Read(p []byte) (int, error) {
	if !e.stripped {
		raw, err := io.ReadAll(e.File)
		if err != nil {
			return 0, err
		}
		raw = stripEmbdBuildTag(raw)
		e.buf = bytes.NewReader(raw)
		e.stripped = true
	}
	return e.buf.Read(p)
}

func (e *embdFile) Stat() (fs.FileInfo, error) {
	fi, err := e.File.Stat()
	if err != nil {
		return nil, err
	}
	return &mangledFileInfo{FileInfo: fi, name: e.name, perm: e.perm}, nil
}

// permFileInfo wraps fs.FileInfo and overrides Mode() to apply correct perm bits.
type permFileInfo struct {
	fs.FileInfo
	perm fs.FileMode
}

func (p *permFileInfo) Mode() fs.FileMode {
	base := p.FileInfo.Mode()
	if base.IsDir() {
		return base.Type() | 0755
	}
	if base.Type()&fs.ModeType != 0 {
		return base // preserve special types (symlinks etc.)
	}
	return base.Type() | p.perm
}

// mangledFileInfo wraps fs.FileInfo but returns a custom name and permission.
type mangledFileInfo struct {
	fs.FileInfo
	name string
	perm fs.FileMode
}

func (m *mangledFileInfo) Name() string { return m.name }
func (m *mangledFileInfo) Mode() fs.FileMode {
	base := m.FileInfo.Mode()
	if base.IsDir() {
		return base.Type() | 0755
	}
	return base.Type() | m.perm
}

// symlinkFileInfo wraps fs.FileInfo, reports a custom name and ModeSymlink.
type symlinkFileInfo struct {
	fs.FileInfo
	name string
}

func (s *symlinkFileInfo) Name() string       { return s.name }
func (s *symlinkFileInfo) Mode() fs.FileMode  { return fs.ModeSymlink | 0777 }
func (s *symlinkFileInfo) Size() int64        { return 0 }
func (s *symlinkFileInfo) ModTime() time.Time { return s.FileInfo.ModTime() }
func (s *symlinkFileInfo) IsDir() bool        { return false }
func (s *symlinkFileInfo) Sys() interface{}   { return nil }

// permDirEntry wraps a DirEntry and applies correct permission on Info().
type permDirEntry struct {
	fs.DirEntry
	perm fs.FileMode
}

func (p *permDirEntry) Info() (fs.FileInfo, error) {
	fi, err := p.DirEntry.Info()
	if err != nil {
		return nil, err
	}
	return &permFileInfo{FileInfo: fi, perm: p.perm}, nil
}

// mangledDirEntry wraps a DirEntry and reports a custom name and permission.
type mangledDirEntry struct {
	fs.DirEntry
	name string
	perm fs.FileMode
}

func (m *mangledDirEntry) Name() string { return m.name }
func (m *mangledDirEntry) Info() (fs.FileInfo, error) {
	fi, err := m.DirEntry.Info()
	if err != nil {
		return nil, err
	}
	return &mangledFileInfo{FileInfo: fi, name: m.name, perm: m.perm}, nil
}

// symlinkDirEntry wraps a DirEntry and presents it as a symlink.
type symlinkDirEntry struct {
	fs.DirEntry
	name string
}

func (s *symlinkDirEntry) Name() string      { return s.name }
func (s *symlinkDirEntry) Type() fs.FileMode { return fs.ModeSymlink }
func (s *symlinkDirEntry) IsDir() bool       { return false }
func (s *symlinkDirEntry) Info() (fs.FileInfo, error) {
	fi, err := s.DirEntry.Info()
	if err != nil {
		return nil, err
	}
	return &symlinkFileInfo{FileInfo: fi, name: s.name}, nil
}
