#!/usr/bin/env bash

# AUTOGENERATED FILE - edit versions in ./component-versions.json.
# If you want to add/modify these components, please read the how-to steps in
# ./cmd/components/main.go.
# You can regenerate with "make hack-generate-components".

set_versions() {
	# Note: Kubernetes Version node image per Kind releases (full hash is suggested):
	# https://github.com/kubernetes-sigs/kind/releases
	kind_node_version=v1.32.0@sha256:c48c62eac5da28cdadcf560d1d8616cfa6783b58f0d94cf63ad1bf49600cb027

	# find source-of-truth in component-versions.json to add/modify components
	knative_serving_version="v1.20.0"
	knative_eventing_version="v1.20.0"
	contour_version="v1.20.0"
	tekton_version="v1.1.0"
	pac_version="v0.35.2"
}
