#!/usr/bin/env bash

# AUTOGENERATED FILE - edit versions in ./component-versions.json.
# If you want to add/modify these components, please read the how-to steps in
# ./cmd/components/main.go.
# You can regenerate with "make hack-generate-components".

set_versions() {
	# Note: Kubernetes Version node image per Kind releases (full hash is suggested):
	# https://github.com/kubernetes-sigs/kind/releases
	kind_node_version=v1.34.0@sha256:7416a61b42b1662ca6ca89f02028ac133a309a2a30ba309614e8ec94d976dc5a

	# find source-of-truth in component-versions.json to add/modify components
	knative_serving_version="v1.21.0"
	knative_eventing_version="v1.21.0"
	contour_version="v1.21.0"
	tekton_version="v1.1.0"
	pac_version="v0.35.2"
	keda_version="v2.17.0"
	keda_http_addon_version="v0.12.0"
}
