package main

import (
	"context"
	"encoding/json"
	"fmt"
	"html/template"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"time"

	github "github.com/google/go-github/v68/github"
)

const (
	fileScript             string = "component-versions.sh"
	fileJson               string = "component-versions.json"
	versionsScriptTemplate string = `#!/usr/bin/env bash

# AUTOGENERATED FILE - edit versions in ./component-versions.json.
# If you are adding components, modify this scripts' template in
# ./update-knative-components.go

set_versions() {
	# Note: Kubernetes Version node image per Kind releases (full hash is suggested):
	# https://github.com/kubernetes-sigs/kind/releases
	kind_node_version={{.KindNode}}

	// gets updated programatically via workflow -> PR creation
	knative_serving_version="{{.Serving}}"
	knative_eventing_version="{{.Eventing}}"
	contour_version="{{.Contour}}"
}
`
)

// all the components that are kept up to date
type Versions struct {
	KindNode string
	Serving  string
	Eventing string
	Contour  string
}

// entry function -- essentially "func main()" for this file
func updateComponentVersions(ctx context.Context) error {
	const prTitle = "chore: Update components' versions to latest"
	client := github.NewClient(nil).WithAuthToken(os.Getenv("GITHUB_TOKEN"))

	e, err := prExists(ctx, client, prTitle)
	if err != nil {
		return err
	}
	if e {
		fmt.Printf("PR already exists, nothing to do, exiting")
		return nil
	}

	projects := []struct {
		owner, repo string
	}{
		{
			owner: "knative",
			repo:  "serving",
		},
		{
			owner: "knative",
			repo:  "eventing",
		},
		{
			owner: "knative-extensions",
			repo:  "net-contour",
		},
	}

	// Get current versions used.
	v, err := readVersions(fileJson)
	if err != nil {
		return err
	}

	updated := false
	// cycle through all versions of components listed above, fetch their
	// latest from github releases - cmp them - create PR for update if necessary
	for _, p := range projects {
		newV, err := getLatestVersion(ctx, client, p.owner, p.repo)
		if err != nil {
			return fmt.Errorf("error while getting latest v of %s/%s: %v", p.owner, p.repo, err)
		}

		// try to overwrite with possibly new versions
		if updateVersion(&v, p.repo, newV) {
			// if any of the files are updated, set true
			updated = true
		}
	}

	if !updated {
		// nothing was updated, nothing to do
		fmt.Printf("all good, no newer component releases, exiting\n")
		return nil
	}

	if err := writeFiles(v, fileScript, fileJson); err != nil {
		return fmt.Errorf("failed to write files: %v", err)
	}

	fmt.Println("files updated!")

	branchName := "update-components" + time.Now().Format(time.DateOnly)
	err = prepareBranch(branchName)
	if err != nil {
		return fmt.Errorf("failed to prep the branch: %v", err)
	}
	err = createPR(ctx, client, prTitle, branchName)
	return err
}

// read (unmarshal) component versions from .json
func readVersions(file string) (v Versions, err error) {
	data, err := os.ReadFile(file)
	if err != nil {
		return
	}
	err = json.Unmarshal(data, &v)
	return
}

// attempt to update 'v' Versions to new 'val' for specific 'repo'
func updateVersion(v *Versions, repo, val string) (updated bool) {
	fmt.Printf("check for %s update...", repo)
	if repo == "serving" && v.Serving != val {
		v.Serving = val
		updated = true
	} else if repo == "eventing" && v.Eventing != val {
		v.Eventing = val
		updated = true
	} else if repo == "net-contour" && v.Contour != val {
		v.Contour = val
		updated = true
	}
	if updated {
		fmt.Printf("found! new:'%s'\n", val)
	} else {
		fmt.Println("nothing to do")
	}
	return
}

// Overwrite the 'source of truth' file - .json and regenerate new script
// with new versions from 'v'.
// Arguments 'script' & 'json' are paths to files for autogenerated script and
// source (json) file respectively.
func writeFiles(v Versions, script, json string) error {
	// write to json
	err := writeVersionsSource(v, json)
	if err != nil {
		return fmt.Errorf("failed to write to json: %v", err)
	}
	// write to script file
	err = writeVersionsScript(v, script)
	if err != nil {
		return fmt.Errorf("failed to generate script: %v", err)
	}
	return nil
}

// write to 'source of truth' file (json) with updated versions
func writeVersionsSource(v Versions, file string) error {
	vB, err := json.MarshalIndent(v, "", "	")
	if err != nil {
		return fmt.Errorf("cant Marshal versions: %v", err)
	}
	f, err := os.Create(file)
	if err != nil {
		return err
	}
	_, err = f.Write(vB)
	return err
}

// write to autogenerated script file with newest Versions
func writeVersionsScript(v Versions, file string) error {
	tmpl, err := template.New("versions").Parse(versionsScriptTemplate)
	if err != nil {
		return err
	}
	f, err := os.Create(file)
	if err != nil {
		return err
	}
	defer f.Close()

	if err := tmpl.Execute(f, v); err != nil {
		return err
	}
	return nil
}

// get latest version of owner/repo via GH API
func getLatestVersion(ctx context.Context, client *github.Client, owner string, repo string) (v string, err error) {
	fmt.Printf("> get latest '%s/%s'...", owner, repo)
	rr, res, err := client.Repositories.GetLatestRelease(ctx, owner, repo)
	if err != nil {
		err = fmt.Errorf("error: request for latest %s release: %v", owner+"/"+repo, err)
		return
	}
	if res.StatusCode < 200 && res.StatusCode > 299 {
		err = fmt.Errorf("error: Return status code of request for latest %s release is %d", owner+"/"+repo, res.StatusCode)
		return
	}
	v = *rr.Name
	if v == "" {
		return "", fmt.Errorf("internal error: returned latest release name is empty for '%s'", repo)
	}
	fmt.Println("done")
	return v, nil
}

// prepare branch for PR via git commands
func prepareBranch(branchName string) error {
	fmt.Println("> preparing branch")
	cmd := exec.Command("bash", "-c", fmt.Sprintf(`
		git config --local user.email "automation@knative.team" &&
		git config --local user.name "Knative Automation" &&
		git switch -c %s &&
		git add %s %s &&
		git commit -m "update components" &&
		git push origin %s
	`, branchName, fileScript, fileJson, branchName))

	cmd.Stderr = os.Stderr
	cmd.Stdout = os.Stdout
	return cmd.Run()
}

// create a PR for the new updates
func createPR(ctx context.Context, client *github.Client, title string, branchName string) error {
	fmt.Print("> creating PR...")
	body := fmt.Sprintf("%s\n/assign @gauron99", title)

	newPR := github.NewPullRequest{
		Title:               github.Ptr(title),
		Base:                github.Ptr("main"),
		Head:                github.Ptr(branchName),
		Body:                github.Ptr(body),
		MaintainerCanModify: github.Ptr(true),
	}
	pr, _, err := client.PullRequests.Create(ctx, "knative", "func", &newPR)
	if err != nil {
		fmt.Printf("PR looks like this:\n%#v\n", pr)
		fmt.Printf("err: %s\n", err)
		return err
	}
	fmt.Println("ready")
	return nil
}

// returns true when PR with given title already exists in knative/func repo
// otherwise false. Returns an error if occurred, otherwise nil.
func prExists(ctx context.Context, c *github.Client, title string) (bool, error) {
	perPage := 10
	opt := &github.PullRequestListOptions{State: "open", ListOptions: github.ListOptions{PerPage: perPage}}
	for {
		list, resp, err := c.PullRequests.List(ctx, "knative", "func", opt)
		if err != nil {
			return false, fmt.Errorf("errror pulling PRs in knative/func: %s", err)
		}
		for _, pr := range list {
			if pr.GetTitle() == title {
				// gauron99 - currently cannot update already existing PR
				return true, nil
			}
		}
		if resp.NextPage == 0 {
			// hit end of list
			return false, nil
		}
		// otherwise, continue to the next page
		opt.Page = resp.NextPage
	}
}

// -------------------------------------------------------------------------- \\
// -------------------------------------------------------------------------- \\
// -------------------------------------------------------------------------- \\
// -------------------------------------------------------------------------- \\

// This file collects the functions from above to generate(write) the files ONLY.
// It doesnt pull anything from repos, github APIs etc, just rewrites of the
// autogen file based off of json and json itself for file sync purposes
// It is to be used localy:
func generateComponentVersions() error {
	pathPrefix := "" // path prefix
	fromRoot, err := isRunFromRoot()
	if err != nil {
		return err
	}
	if fromRoot {
		pathPrefix = "hack"
	}

	// get correct relative path to files
	relJson := path.Join(pathPrefix, fileJson)
	relScript := path.Join(pathPrefix, fileScript)

	v, err := readVersions(relJson)
	if err != nil {
		return fmt.Errorf("failed to read Versions from json: %v", err)
	}
	// generate
	err = writeFiles(v, relScript, relJson)
	if err != nil {
		return fmt.Errorf("failed to write Versions: %v", err)
	}
	return nil
}

func isRunFromRoot() (bool, error) {
	wd, err := os.Getwd()
	if err != nil {
		return false, fmt.Errorf("Error getting cwd: %v", err)
	}
	fmt.Printf("wd: '%v'\n", wd)

	// Check if the last directory in the path is "hack"
	return filepath.Base(wd) != "hack", nil
}
