// Code generated by gen_close_guard.go; DO NOT EDIT.

package docker

import (
	"context"
	"io"

	"github.com/moby/moby/client"
)

func (c *closeGuardingClient) ContainerAttach(arg0 context.Context, arg1 string, arg2 client.ContainerAttachOptions) (client.ContainerAttachResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerAttach(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerCommit(arg0 context.Context, arg1 string, arg2 client.ContainerCommitOptions) (client.ContainerCommitResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerCommit(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerCreate(arg0 context.Context, arg1 client.ContainerCreateOptions) (client.ContainerCreateResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerCreate(arg0, arg1)
}

func (c *closeGuardingClient) ContainerInspect(arg0 context.Context, arg1 string, arg2 client.ContainerInspectOptions) (client.ContainerInspectResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerInspect(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerKill(arg0 context.Context, arg1 string, arg2 client.ContainerKillOptions) (client.ContainerKillResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerKill(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerRemove(arg0 context.Context, arg1 string, arg2 client.ContainerRemoveOptions) (client.ContainerRemoveResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerRemove(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerStart(arg0 context.Context, arg1 string, arg2 client.ContainerStartOptions) (client.ContainerStartResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerStart(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerStop(arg0 context.Context, arg1 string, arg2 client.ContainerStopOptions) (client.ContainerStopResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerStop(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerWait(arg0 context.Context, arg1 string, arg2 client.ContainerWaitOptions) client.ContainerWaitResult {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerWait(arg0, arg1, arg2)
}

func (c *closeGuardingClient) CopyFromContainer(arg0 context.Context, arg1 string, arg2 client.CopyFromContainerOptions) (client.CopyFromContainerResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.CopyFromContainer(arg0, arg1, arg2)
}

func (c *closeGuardingClient) CopyToContainer(arg0 context.Context, arg1 string, arg2 client.CopyToContainerOptions) (client.CopyToContainerResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.CopyToContainer(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ImageBuild(arg0 context.Context, arg1 io.Reader, arg2 client.ImageBuildOptions) (client.ImageBuildResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ImageBuild(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ImageHistory(arg0 context.Context, arg1 string, arg2 ...client.ImageHistoryOption) (client.ImageHistoryResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ImageHistory(arg0, arg1, arg2...)
}

func (c *closeGuardingClient) ImageInspect(arg0 context.Context, arg1 string, arg2 ...client.ImageInspectOption) (client.ImageInspectResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ImageInspect(arg0, arg1, arg2...)
}

func (c *closeGuardingClient) ImageLoad(arg0 context.Context, arg1 io.Reader, arg2 ...client.ImageLoadOption) (client.ImageLoadResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ImageLoad(arg0, arg1, arg2...)
}

func (c *closeGuardingClient) ImagePull(arg0 context.Context, arg1 string, arg2 client.ImagePullOptions) (client.ImagePullResponse, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ImagePull(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ImagePush(arg0 context.Context, arg1 string, arg2 client.ImagePushOptions) (client.ImagePushResponse, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ImagePush(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ImageRemove(arg0 context.Context, arg1 string, arg2 client.ImageRemoveOptions) (client.ImageRemoveResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ImageRemove(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ImageSave(arg0 context.Context, arg1 []string, arg2 ...client.ImageSaveOption) (client.ImageSaveResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ImageSave(arg0, arg1, arg2...)
}

func (c *closeGuardingClient) ImageTag(arg0 context.Context, arg1 client.ImageTagOptions) (client.ImageTagResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ImageTag(arg0, arg1)
}

func (c *closeGuardingClient) Info(arg0 context.Context, arg1 client.InfoOptions) (client.SystemInfoResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.Info(arg0, arg1)
}

func (c *closeGuardingClient) NetworkCreate(arg0 context.Context, arg1 string, arg2 client.NetworkCreateOptions) (client.NetworkCreateResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.NetworkCreate(arg0, arg1, arg2)
}

func (c *closeGuardingClient) NetworkRemove(arg0 context.Context, arg1 string, arg2 client.NetworkRemoveOptions) (client.NetworkRemoveResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.NetworkRemove(arg0, arg1, arg2)
}

func (c *closeGuardingClient) Ping(arg0 context.Context, arg1 client.PingOptions) (client.PingResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.Ping(arg0, arg1)
}

func (c *closeGuardingClient) ServerVersion(arg0 context.Context, arg1 client.ServerVersionOptions) (client.ServerVersionResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ServerVersion(arg0, arg1)
}

func (c *closeGuardingClient) VolumeList(arg0 context.Context, arg1 client.VolumeListOptions) (client.VolumeListResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.VolumeList(arg0, arg1)
}

func (c *closeGuardingClient) VolumeRemove(arg0 context.Context, arg1 string, arg2 client.VolumeRemoveOptions) (client.VolumeRemoveResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.VolumeRemove(arg0, arg1, arg2)
}
