// Code generated by gen-close-guard; DO NOT EDIT.

package docker

import (
	"context"
	"io"
	"net"

	mobyClient "github.com/moby/moby/client"
)

func (c *closeGuardingClient) BuildCachePrune(arg0 context.Context, arg1 mobyClient.BuildCachePruneOptions) (mobyClient.BuildCachePruneResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.BuildCachePrune(arg0, arg1)
}

func (c *closeGuardingClient) BuildCancel(arg0 context.Context, arg1 string, arg2 mobyClient.BuildCancelOptions) (mobyClient.BuildCancelResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.BuildCancel(arg0, arg1, arg2)
}

func (c *closeGuardingClient) CheckpointCreate(arg0 context.Context, arg1 string, arg2 mobyClient.CheckpointCreateOptions) (mobyClient.CheckpointCreateResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.CheckpointCreate(arg0, arg1, arg2)
}

func (c *closeGuardingClient) CheckpointList(arg0 context.Context, arg1 string, arg2 mobyClient.CheckpointListOptions) (mobyClient.CheckpointListResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.CheckpointList(arg0, arg1, arg2)
}

func (c *closeGuardingClient) CheckpointRemove(arg0 context.Context, arg1 string, arg2 mobyClient.CheckpointRemoveOptions) (mobyClient.CheckpointRemoveResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.CheckpointRemove(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ClientVersion() string {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ClientVersion()
}

func (c *closeGuardingClient) ConfigCreate(arg0 context.Context, arg1 mobyClient.ConfigCreateOptions) (mobyClient.ConfigCreateResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ConfigCreate(arg0, arg1)
}

func (c *closeGuardingClient) ConfigInspect(arg0 context.Context, arg1 string, arg2 mobyClient.ConfigInspectOptions) (mobyClient.ConfigInspectResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ConfigInspect(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ConfigList(arg0 context.Context, arg1 mobyClient.ConfigListOptions) (mobyClient.ConfigListResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ConfigList(arg0, arg1)
}

func (c *closeGuardingClient) ConfigRemove(arg0 context.Context, arg1 string, arg2 mobyClient.ConfigRemoveOptions) (mobyClient.ConfigRemoveResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ConfigRemove(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ConfigUpdate(arg0 context.Context, arg1 string, arg2 mobyClient.ConfigUpdateOptions) (mobyClient.ConfigUpdateResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ConfigUpdate(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerAttach(arg0 context.Context, arg1 string, arg2 mobyClient.ContainerAttachOptions) (mobyClient.ContainerAttachResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerAttach(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerCommit(arg0 context.Context, arg1 string, arg2 mobyClient.ContainerCommitOptions) (mobyClient.ContainerCommitResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerCommit(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerCreate(arg0 context.Context, arg1 mobyClient.ContainerCreateOptions) (mobyClient.ContainerCreateResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerCreate(arg0, arg1)
}

func (c *closeGuardingClient) ContainerDiff(arg0 context.Context, arg1 string, arg2 mobyClient.ContainerDiffOptions) (mobyClient.ContainerDiffResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerDiff(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerExport(arg0 context.Context, arg1 string, arg2 mobyClient.ContainerExportOptions) (mobyClient.ContainerExportResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerExport(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerInspect(arg0 context.Context, arg1 string, arg2 mobyClient.ContainerInspectOptions) (mobyClient.ContainerInspectResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerInspect(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerKill(arg0 context.Context, arg1 string, arg2 mobyClient.ContainerKillOptions) (mobyClient.ContainerKillResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerKill(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerList(arg0 context.Context, arg1 mobyClient.ContainerListOptions) (mobyClient.ContainerListResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerList(arg0, arg1)
}

func (c *closeGuardingClient) ContainerLogs(arg0 context.Context, arg1 string, arg2 mobyClient.ContainerLogsOptions) (mobyClient.ContainerLogsResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerLogs(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerPause(arg0 context.Context, arg1 string, arg2 mobyClient.ContainerPauseOptions) (mobyClient.ContainerPauseResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerPause(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerPrune(arg0 context.Context, arg1 mobyClient.ContainerPruneOptions) (mobyClient.ContainerPruneResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerPrune(arg0, arg1)
}

func (c *closeGuardingClient) ContainerRemove(arg0 context.Context, arg1 string, arg2 mobyClient.ContainerRemoveOptions) (mobyClient.ContainerRemoveResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerRemove(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerRename(arg0 context.Context, arg1 string, arg2 mobyClient.ContainerRenameOptions) (mobyClient.ContainerRenameResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerRename(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerResize(arg0 context.Context, arg1 string, arg2 mobyClient.ContainerResizeOptions) (mobyClient.ContainerResizeResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerResize(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerRestart(arg0 context.Context, arg1 string, arg2 mobyClient.ContainerRestartOptions) (mobyClient.ContainerRestartResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerRestart(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerStart(arg0 context.Context, arg1 string, arg2 mobyClient.ContainerStartOptions) (mobyClient.ContainerStartResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerStart(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerStatPath(arg0 context.Context, arg1 string, arg2 mobyClient.ContainerStatPathOptions) (mobyClient.ContainerStatPathResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerStatPath(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerStats(arg0 context.Context, arg1 string, arg2 mobyClient.ContainerStatsOptions) (mobyClient.ContainerStatsResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerStats(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerStop(arg0 context.Context, arg1 string, arg2 mobyClient.ContainerStopOptions) (mobyClient.ContainerStopResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerStop(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerTop(arg0 context.Context, arg1 string, arg2 mobyClient.ContainerTopOptions) (mobyClient.ContainerTopResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerTop(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerUnpause(arg0 context.Context, arg1 string, arg2 mobyClient.ContainerUnpauseOptions) (mobyClient.ContainerUnpauseResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerUnpause(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerUpdate(arg0 context.Context, arg1 string, arg2 mobyClient.ContainerUpdateOptions) (mobyClient.ContainerUpdateResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerUpdate(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ContainerWait(arg0 context.Context, arg1 string, arg2 mobyClient.ContainerWaitOptions) mobyClient.ContainerWaitResult {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ContainerWait(arg0, arg1, arg2)
}

func (c *closeGuardingClient) CopyFromContainer(arg0 context.Context, arg1 string, arg2 mobyClient.CopyFromContainerOptions) (mobyClient.CopyFromContainerResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.CopyFromContainer(arg0, arg1, arg2)
}

func (c *closeGuardingClient) CopyToContainer(arg0 context.Context, arg1 string, arg2 mobyClient.CopyToContainerOptions) (mobyClient.CopyToContainerResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.CopyToContainer(arg0, arg1, arg2)
}

func (c *closeGuardingClient) DaemonHost() string {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.DaemonHost()
}

func (c *closeGuardingClient) DialHijack(arg0 context.Context, arg1 string, arg2 string, arg3 map[string][]string) (net.Conn, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.DialHijack(arg0, arg1, arg2, arg3)
}

func (c *closeGuardingClient) Dialer() func(context.Context) (net.Conn, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.Dialer()
}

func (c *closeGuardingClient) DiskUsage(arg0 context.Context, arg1 mobyClient.DiskUsageOptions) (mobyClient.DiskUsageResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.DiskUsage(arg0, arg1)
}

func (c *closeGuardingClient) DistributionInspect(arg0 context.Context, arg1 string, arg2 mobyClient.DistributionInspectOptions) (mobyClient.DistributionInspectResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.DistributionInspect(arg0, arg1, arg2)
}

func (c *closeGuardingClient) Events(arg0 context.Context, arg1 mobyClient.EventsListOptions) mobyClient.EventsResult {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.Events(arg0, arg1)
}

func (c *closeGuardingClient) ExecAttach(arg0 context.Context, arg1 string, arg2 mobyClient.ExecAttachOptions) (mobyClient.ExecAttachResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ExecAttach(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ExecCreate(arg0 context.Context, arg1 string, arg2 mobyClient.ExecCreateOptions) (mobyClient.ExecCreateResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ExecCreate(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ExecInspect(arg0 context.Context, arg1 string, arg2 mobyClient.ExecInspectOptions) (mobyClient.ExecInspectResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ExecInspect(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ExecResize(arg0 context.Context, arg1 string, arg2 mobyClient.ExecResizeOptions) (mobyClient.ExecResizeResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ExecResize(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ExecStart(arg0 context.Context, arg1 string, arg2 mobyClient.ExecStartOptions) (mobyClient.ExecStartResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ExecStart(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ImageBuild(arg0 context.Context, arg1 io.Reader, arg2 mobyClient.ImageBuildOptions) (mobyClient.ImageBuildResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ImageBuild(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ImageHistory(arg0 context.Context, arg1 string, arg2 ...mobyClient.ImageHistoryOption) (mobyClient.ImageHistoryResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ImageHistory(arg0, arg1, arg2...)
}

func (c *closeGuardingClient) ImageImport(arg0 context.Context, arg1 mobyClient.ImageImportSource, arg2 string, arg3 mobyClient.ImageImportOptions) (mobyClient.ImageImportResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ImageImport(arg0, arg1, arg2, arg3)
}

func (c *closeGuardingClient) ImageInspect(arg0 context.Context, arg1 string, arg2 ...mobyClient.ImageInspectOption) (mobyClient.ImageInspectResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ImageInspect(arg0, arg1, arg2...)
}

func (c *closeGuardingClient) ImageList(arg0 context.Context, arg1 mobyClient.ImageListOptions) (mobyClient.ImageListResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ImageList(arg0, arg1)
}

func (c *closeGuardingClient) ImageLoad(arg0 context.Context, arg1 io.Reader, arg2 ...mobyClient.ImageLoadOption) (mobyClient.ImageLoadResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ImageLoad(arg0, arg1, arg2...)
}

func (c *closeGuardingClient) ImagePrune(arg0 context.Context, arg1 mobyClient.ImagePruneOptions) (mobyClient.ImagePruneResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ImagePrune(arg0, arg1)
}

func (c *closeGuardingClient) ImagePull(arg0 context.Context, arg1 string, arg2 mobyClient.ImagePullOptions) (mobyClient.ImagePullResponse, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ImagePull(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ImagePush(arg0 context.Context, arg1 string, arg2 mobyClient.ImagePushOptions) (mobyClient.ImagePushResponse, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ImagePush(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ImageRemove(arg0 context.Context, arg1 string, arg2 mobyClient.ImageRemoveOptions) (mobyClient.ImageRemoveResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ImageRemove(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ImageSave(arg0 context.Context, arg1 []string, arg2 ...mobyClient.ImageSaveOption) (mobyClient.ImageSaveResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ImageSave(arg0, arg1, arg2...)
}

func (c *closeGuardingClient) ImageSearch(arg0 context.Context, arg1 string, arg2 mobyClient.ImageSearchOptions) (mobyClient.ImageSearchResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ImageSearch(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ImageTag(arg0 context.Context, arg1 mobyClient.ImageTagOptions) (mobyClient.ImageTagResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ImageTag(arg0, arg1)
}

func (c *closeGuardingClient) Info(arg0 context.Context, arg1 mobyClient.InfoOptions) (mobyClient.SystemInfoResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.Info(arg0, arg1)
}

func (c *closeGuardingClient) NetworkConnect(arg0 context.Context, arg1 string, arg2 mobyClient.NetworkConnectOptions) (mobyClient.NetworkConnectResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.NetworkConnect(arg0, arg1, arg2)
}

func (c *closeGuardingClient) NetworkCreate(arg0 context.Context, arg1 string, arg2 mobyClient.NetworkCreateOptions) (mobyClient.NetworkCreateResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.NetworkCreate(arg0, arg1, arg2)
}

func (c *closeGuardingClient) NetworkDisconnect(arg0 context.Context, arg1 string, arg2 mobyClient.NetworkDisconnectOptions) (mobyClient.NetworkDisconnectResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.NetworkDisconnect(arg0, arg1, arg2)
}

func (c *closeGuardingClient) NetworkInspect(arg0 context.Context, arg1 string, arg2 mobyClient.NetworkInspectOptions) (mobyClient.NetworkInspectResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.NetworkInspect(arg0, arg1, arg2)
}

func (c *closeGuardingClient) NetworkList(arg0 context.Context, arg1 mobyClient.NetworkListOptions) (mobyClient.NetworkListResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.NetworkList(arg0, arg1)
}

func (c *closeGuardingClient) NetworkPrune(arg0 context.Context, arg1 mobyClient.NetworkPruneOptions) (mobyClient.NetworkPruneResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.NetworkPrune(arg0, arg1)
}

func (c *closeGuardingClient) NetworkRemove(arg0 context.Context, arg1 string, arg2 mobyClient.NetworkRemoveOptions) (mobyClient.NetworkRemoveResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.NetworkRemove(arg0, arg1, arg2)
}

func (c *closeGuardingClient) NodeInspect(arg0 context.Context, arg1 string, arg2 mobyClient.NodeInspectOptions) (mobyClient.NodeInspectResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.NodeInspect(arg0, arg1, arg2)
}

func (c *closeGuardingClient) NodeList(arg0 context.Context, arg1 mobyClient.NodeListOptions) (mobyClient.NodeListResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.NodeList(arg0, arg1)
}

func (c *closeGuardingClient) NodeRemove(arg0 context.Context, arg1 string, arg2 mobyClient.NodeRemoveOptions) (mobyClient.NodeRemoveResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.NodeRemove(arg0, arg1, arg2)
}

func (c *closeGuardingClient) NodeUpdate(arg0 context.Context, arg1 string, arg2 mobyClient.NodeUpdateOptions) (mobyClient.NodeUpdateResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.NodeUpdate(arg0, arg1, arg2)
}

func (c *closeGuardingClient) Ping(arg0 context.Context, arg1 mobyClient.PingOptions) (mobyClient.PingResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.Ping(arg0, arg1)
}

func (c *closeGuardingClient) PluginCreate(arg0 context.Context, arg1 io.Reader, arg2 mobyClient.PluginCreateOptions) (mobyClient.PluginCreateResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.PluginCreate(arg0, arg1, arg2)
}

func (c *closeGuardingClient) PluginDisable(arg0 context.Context, arg1 string, arg2 mobyClient.PluginDisableOptions) (mobyClient.PluginDisableResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.PluginDisable(arg0, arg1, arg2)
}

func (c *closeGuardingClient) PluginEnable(arg0 context.Context, arg1 string, arg2 mobyClient.PluginEnableOptions) (mobyClient.PluginEnableResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.PluginEnable(arg0, arg1, arg2)
}

func (c *closeGuardingClient) PluginInspect(arg0 context.Context, arg1 string, arg2 mobyClient.PluginInspectOptions) (mobyClient.PluginInspectResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.PluginInspect(arg0, arg1, arg2)
}

func (c *closeGuardingClient) PluginInstall(arg0 context.Context, arg1 string, arg2 mobyClient.PluginInstallOptions) (mobyClient.PluginInstallResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.PluginInstall(arg0, arg1, arg2)
}

func (c *closeGuardingClient) PluginList(arg0 context.Context, arg1 mobyClient.PluginListOptions) (mobyClient.PluginListResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.PluginList(arg0, arg1)
}

func (c *closeGuardingClient) PluginPush(arg0 context.Context, arg1 string, arg2 mobyClient.PluginPushOptions) (mobyClient.PluginPushResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.PluginPush(arg0, arg1, arg2)
}

func (c *closeGuardingClient) PluginRemove(arg0 context.Context, arg1 string, arg2 mobyClient.PluginRemoveOptions) (mobyClient.PluginRemoveResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.PluginRemove(arg0, arg1, arg2)
}

func (c *closeGuardingClient) PluginSet(arg0 context.Context, arg1 string, arg2 mobyClient.PluginSetOptions) (mobyClient.PluginSetResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.PluginSet(arg0, arg1, arg2)
}

func (c *closeGuardingClient) PluginUpgrade(arg0 context.Context, arg1 string, arg2 mobyClient.PluginUpgradeOptions) (mobyClient.PluginUpgradeResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.PluginUpgrade(arg0, arg1, arg2)
}

func (c *closeGuardingClient) RegistryLogin(arg0 context.Context, arg1 mobyClient.RegistryLoginOptions) (mobyClient.RegistryLoginResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.RegistryLogin(arg0, arg1)
}

func (c *closeGuardingClient) SecretCreate(arg0 context.Context, arg1 mobyClient.SecretCreateOptions) (mobyClient.SecretCreateResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.SecretCreate(arg0, arg1)
}

func (c *closeGuardingClient) SecretInspect(arg0 context.Context, arg1 string, arg2 mobyClient.SecretInspectOptions) (mobyClient.SecretInspectResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.SecretInspect(arg0, arg1, arg2)
}

func (c *closeGuardingClient) SecretList(arg0 context.Context, arg1 mobyClient.SecretListOptions) (mobyClient.SecretListResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.SecretList(arg0, arg1)
}

func (c *closeGuardingClient) SecretRemove(arg0 context.Context, arg1 string, arg2 mobyClient.SecretRemoveOptions) (mobyClient.SecretRemoveResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.SecretRemove(arg0, arg1, arg2)
}

func (c *closeGuardingClient) SecretUpdate(arg0 context.Context, arg1 string, arg2 mobyClient.SecretUpdateOptions) (mobyClient.SecretUpdateResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.SecretUpdate(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ServerVersion(arg0 context.Context, arg1 mobyClient.ServerVersionOptions) (mobyClient.ServerVersionResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ServerVersion(arg0, arg1)
}

func (c *closeGuardingClient) ServiceCreate(arg0 context.Context, arg1 mobyClient.ServiceCreateOptions) (mobyClient.ServiceCreateResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ServiceCreate(arg0, arg1)
}

func (c *closeGuardingClient) ServiceInspect(arg0 context.Context, arg1 string, arg2 mobyClient.ServiceInspectOptions) (mobyClient.ServiceInspectResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ServiceInspect(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ServiceList(arg0 context.Context, arg1 mobyClient.ServiceListOptions) (mobyClient.ServiceListResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ServiceList(arg0, arg1)
}

func (c *closeGuardingClient) ServiceLogs(arg0 context.Context, arg1 string, arg2 mobyClient.ServiceLogsOptions) (mobyClient.ServiceLogsResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ServiceLogs(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ServiceRemove(arg0 context.Context, arg1 string, arg2 mobyClient.ServiceRemoveOptions) (mobyClient.ServiceRemoveResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ServiceRemove(arg0, arg1, arg2)
}

func (c *closeGuardingClient) ServiceUpdate(arg0 context.Context, arg1 string, arg2 mobyClient.ServiceUpdateOptions) (mobyClient.ServiceUpdateResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.ServiceUpdate(arg0, arg1, arg2)
}

func (c *closeGuardingClient) SwarmGetUnlockKey(arg0 context.Context) (mobyClient.SwarmGetUnlockKeyResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.SwarmGetUnlockKey(arg0)
}

func (c *closeGuardingClient) SwarmInit(arg0 context.Context, arg1 mobyClient.SwarmInitOptions) (mobyClient.SwarmInitResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.SwarmInit(arg0, arg1)
}

func (c *closeGuardingClient) SwarmInspect(arg0 context.Context, arg1 mobyClient.SwarmInspectOptions) (mobyClient.SwarmInspectResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.SwarmInspect(arg0, arg1)
}

func (c *closeGuardingClient) SwarmJoin(arg0 context.Context, arg1 mobyClient.SwarmJoinOptions) (mobyClient.SwarmJoinResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.SwarmJoin(arg0, arg1)
}

func (c *closeGuardingClient) SwarmLeave(arg0 context.Context, arg1 mobyClient.SwarmLeaveOptions) (mobyClient.SwarmLeaveResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.SwarmLeave(arg0, arg1)
}

func (c *closeGuardingClient) SwarmUnlock(arg0 context.Context, arg1 mobyClient.SwarmUnlockOptions) (mobyClient.SwarmUnlockResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.SwarmUnlock(arg0, arg1)
}

func (c *closeGuardingClient) SwarmUpdate(arg0 context.Context, arg1 mobyClient.SwarmUpdateOptions) (mobyClient.SwarmUpdateResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.SwarmUpdate(arg0, arg1)
}

func (c *closeGuardingClient) TaskInspect(arg0 context.Context, arg1 string, arg2 mobyClient.TaskInspectOptions) (mobyClient.TaskInspectResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.TaskInspect(arg0, arg1, arg2)
}

func (c *closeGuardingClient) TaskList(arg0 context.Context, arg1 mobyClient.TaskListOptions) (mobyClient.TaskListResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.TaskList(arg0, arg1)
}

func (c *closeGuardingClient) TaskLogs(arg0 context.Context, arg1 string, arg2 mobyClient.TaskLogsOptions) (mobyClient.TaskLogsResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.TaskLogs(arg0, arg1, arg2)
}

func (c *closeGuardingClient) VolumeCreate(arg0 context.Context, arg1 mobyClient.VolumeCreateOptions) (mobyClient.VolumeCreateResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.VolumeCreate(arg0, arg1)
}

func (c *closeGuardingClient) VolumeInspect(arg0 context.Context, arg1 string, arg2 mobyClient.VolumeInspectOptions) (mobyClient.VolumeInspectResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.VolumeInspect(arg0, arg1, arg2)
}

func (c *closeGuardingClient) VolumeList(arg0 context.Context, arg1 mobyClient.VolumeListOptions) (mobyClient.VolumeListResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.VolumeList(arg0, arg1)
}

func (c *closeGuardingClient) VolumePrune(arg0 context.Context, arg1 mobyClient.VolumePruneOptions) (mobyClient.VolumePruneResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.VolumePrune(arg0, arg1)
}

func (c *closeGuardingClient) VolumeRemove(arg0 context.Context, arg1 string, arg2 mobyClient.VolumeRemoveOptions) (mobyClient.VolumeRemoveResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.VolumeRemove(arg0, arg1, arg2)
}

func (c *closeGuardingClient) VolumeUpdate(arg0 context.Context, arg1 string, arg2 mobyClient.VolumeUpdateOptions) (mobyClient.VolumeUpdateResult, error) {
	c.m.RLock()
	defer c.m.RUnlock()
	if c.closed {
		panic("use of closed client")
	}
	return c.pimpl.VolumeUpdate(arg0, arg1, arg2)
}
