apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: func-deploy
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: CLI
    tekton.dev/tags: cli
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This Task performs a deploy operation using the Knative `func` CLI
  params:
  - name: path
    description: Path to the function project
    default: ""
  workspaces:
    - name: source
      description: The workspace containing the function project
  steps:
  - name: func-deploy
    image: "ghcr.io/knative-sandbox/kn-plugin-func/func:latest"
    command: ["func"]
    args:
      - "deploy"
      - "--verbose"
      - "--build=disabled"
      - "--push=false"
      - "--path"
      - "$(params.path)"
