# Git Server used by OnCluster tests on Openshift CI
# Default Image is ghcr.io/jrangelramos/gitserver-unpriv:latest
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: gitserver
  name: gitserver
spec:
  containers:
    - image: _GITSERVER_IMAGE_
      name: user-container
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gitserver
spec:
  type: NodePort
  selector:
    app: gitserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
