// Command permissions generates templates/.permissions — a manifest of files
// whose permissions differ from the defaults assumed by manglingFS:
//
//	regular file: 0644
//	directory:    0755 (not tracked)
//	symlink:      not tracked (handled via .symlink marker files)
//
// Only files with permissions OTHER than 0644 are listed. The manifest is
// committed to the repo so that manglingFS (backed by embed.FS, which drops
// all permission bits) can restore the original values at runtime.
//
// Format: one entry per line:
//
//	<octal-mode> <path-relative-to-templates/>
//
// Example:
//
//	0755 quarkus/cloudevents/mvnw
//
// Usage:
//
//	go run ./hack/cmd/permissiongen [check]
//
// Without arguments: regenerates templates/.permissions.
// With "check": verifies it is up to date (exits non-zero if not).
package main

import (
	"bytes"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

const (
	manifestPath  = "templates/.permissions"
	standardFile  = fs.FileMode(0644)
	standardDir   = fs.FileMode(0755)
	executableBit = fs.FileMode(0111)
)

func main() {
	check := len(os.Args) > 1 && os.Args[1] == "check"

	repoRoot, err := findRepoRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "cannot find repo root: %v\n", err)
		os.Exit(1)
	}

	content, err := generate(filepath.Join(repoRoot, "templates"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	outPath := filepath.Join(repoRoot, manifestPath)

	if check {
		existing, err := os.ReadFile(outPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "cannot read %s: %v\n", manifestPath, err)
			os.Exit(1)
		}
		if !bytes.Equal(existing, content) {
			fmt.Fprintf(os.Stderr, "%s is out of date. Run: go run ./hack/cmd/permissiongen\n", manifestPath)
			os.Exit(1)
		}
		fmt.Println(manifestPath, "is up to date.")
		return
	}

	if err := os.WriteFile(outPath, content, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "cannot write %s: %v\n", manifestPath, err)
		os.Exit(1)
	}
	fmt.Printf("Generated %s\n", manifestPath)
}

// generate scans templatesDir and returns manifest content listing all regular
// files whose permissions differ from 0644.
func generate(templatesDir string) ([]byte, error) {
	var lines []string

	err := filepath.WalkDir(templatesDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil // directories always 0755; not tracked
		}

		// Resolve symlinks: .symlink marker files (regular) represent symlinks;
		// actual on-disk symlinks are gone after mangling — skip them.
		fi, err := os.Lstat(path)
		if err != nil {
			return err
		}
		if fi.Mode()&fs.ModeSymlink != 0 {
			return nil // real on-disk symlinks: not tracked
		}

		perm := fi.Mode().Perm()
		if perm == standardFile {
			return nil // standard 0644: no entry needed
		}

		rel, err := filepath.Rel(templatesDir, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		lines = append(lines, fmt.Sprintf("0%o %s", perm, rel))
		return nil
	})
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	buf.WriteString("# DO NOT EDIT. Generated by: go run ./hack/cmd/permissiongen\n")
	buf.WriteString("# Non-standard file permissions in templates/.\n")
	buf.WriteString("# Format: <octal-mode> <path>\n")
	for _, l := range lines {
		buf.WriteString(l)
		buf.WriteByte('\n')
	}
	return buf.Bytes(), nil
}

func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			// confirm it's the repo root (has Makefile too)
			if _, err2 := os.Stat(filepath.Join(dir, "Makefile")); err2 == nil {
				return dir, nil
			}
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("repo root not found")
		}
		// Don't traverse into vendor or third_party go.mod directories
		if strings.Contains(dir, "vendor") || strings.Contains(dir, "third_party") {
			return "", fmt.Errorf("repo root not found")
		}
		dir = parent
	}
}
