[project]
name = "function"
description = ""
version = "0.1.0"
requires-python = ">=3.10"
readme = "README.md"
license = "MIT"
dependencies = [
  "httpx"
]
authors = [
  { name="Your Name", email="you@example.com"},
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

