name: Update CA bundle in embedded templates

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    name: Update CA bundle
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: knative/actions/setup-go@main
      - name: Create PR
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: cd hack && go run ./cmd/update-ca-bundle
