name: Update CA bundle in embedded templates

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    name: Update CA bundle
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install NPM deps.
        run: npm install octokit@3.2.1
      - name: Create PR
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: node ./hack/update-ca-bundle.js

